### DATA GATHERING WITH CSV
### tackling the challenges that we might face while data gathering using CSV

In [1]:
import pandas as pd

In [3]:
pd.read_csv('Titanic.csv')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

### TO READ A TSV ( TAB SEPERATED VALUE) WE NEED TO USE CSV---> SEP FEATURE
### ---> CSV SEP FEATURE ---> SEPERATION FEATURE
### CSV ---> amit,28,M ----> SEPERATION = ','
### TSV ---> amit\t28\tM --> SEPERATION = '\t'

In [4]:
pd.read_csv('test_Arabic_tweets_negative_20190413.tsv', sep = '\t')

      neg              حتى الايتونز خربتوه مو صاحين انتو؟؟ 😭
0     neg  واحد تبع النظام السوري يقول أن المخابرات السور...
1     neg  الى متى التعامل السئ للخادمات وعدم احترامهم وك...
2     neg                  رايح جاي ي طحلبي 🐸 #الهلال_الاهلي
3     neg                                 تتمغط ومعها سداع 😫
4     neg  اذا ما كان ألطف كوبل مر عليكم 😭😭💛💛 حظ جانيت بس...
...   ...                                                ...
5762  neg  النوم وانت مكسور ده احساس غبي اللي هو مش قادر ...
5763  neg  استشهاد_الامام_كاظم_الغيظ السلام على المعذب في...
5764  neg                          انا كنت اكل الصحن بكبره 😐
5765  neg  قولوا لي ايش تشوفوا .. مع ملاحظة التلطف لأنه ا...
5766  neg  ✍ إذا أردت أن تعرف شيئا عني إسالني قبل أن تسأل...

[5767 rows x 2 columns]

### header = 1 removes the first row which is column names.
### NAMES PARAMETER ---> Names is going to take a list of names that we can provide to our colmnu names
### INDEC_COL ---> TO KEEP ONE OF COLUMN AS AN INDEX

In [ ]:
pd.read_csv('Titanic.csv', header = 1 ,names = [ 'P_Id', 'Pclass', 'P_Name', 'Gender', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked' ], index_col = 'P_Id')

,Pclass,P_Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
P_Id,,,,,,,,,,
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
...,...,...,...,...,...,...,...,...,...,...
1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

### Use_Cols ---> WHAT COLUMNS WE SHOULD USE TO SHOW OUT ALL THE COLUMNS WE ARE HAVING IN THE DATAFRAME
### Use List to mention all the columns names that are required

In [11]:
pd.read_csv('student_depression_dataset.csv', usecols = ['id','Gender','Age','City','Profession','Academic Pressure','CGPA','Study Satisfaction','Sleep Duration','Dietary Habits','Degree','Have you ever had suicidal thoughts ?','Work/Study Hours','Financial Stress','Family History of Mental Illness','Depression'])

,id,Gender,Age,City,Profession,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,8.97,2.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,5.90,5.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,7.03,5.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,5.59,2.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,8.13,3.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,5.75,5.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,9.40,3.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,6.61,4.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,6.88,2.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,9.24,1.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

### SQUEEZE ---> DataFrame ---> Series ---> Squeeze ---> True ---> Combination of USECOLS and squeeze ---> True

In [15]:
pd.read_csv('Titanic.csv',  usecols = ['Name']).squeeze()

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

### nrows ---> Helps us with fixed number of rows out of the complete table

In [16]:
pd.read_csv('student_depression_dataset.csv', nrows = 100)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,525,Female,34.0,Hyderabad,Student,3.0,0.0,5.32,3.0,0.0,'7-8 hours',Unhealthy,B.Tech,Yes,7.0,4.0,Yes,1
96,529,Male,22.0,Nagpur,Student,4.0,0.0,6.27,4.0,0.0,'5-6 hours',Moderate,B.Com,Yes,10.0,3.0,No,1
97,530,Male,23.0,Lucknow,Student,3.0,0.0,7.70,2.0,0.0,'More than 8 hours',Unhealthy,M.Com,No,11.0,3.0,Yes,0
98,534,Male,24.0,Kalyan,Student,3.0,0.0,9.66,1.0,0.0,'Less than 5 hours',Healthy,M.Pharm,Yes,9.0,1.0,Yes,1
99,535,Male,21.0,Delhi,Student,5.0,0.0,8.10,1.0,0.0,'More than 8 hours',Moderate,B.Arch,Yes,9.0,3.0,No,1

### ENCODING --> MAKE SURE THAT THE DATA WE ARE READING IS IN UTF-8 FORMAT
# ENCODING VALUE = 'LATIN-1'
### ENCODING ---> WHILE WORKING WITH THE NUMERICAL KINDOF DATA --> UTF-8 IS USED
## WHEN THE DATA IS IN PRESENT IN THE TEXT FORMAT OR ANY OTHER NON NUMERICAL DATA 
### ---> THEN WE HAVE TO MANUALLY KEEP THE ENCODING TO --> UTF-8 -> TO READ THE CONTENT

In [17]:
pd.read_csv('Titanic.csv', encoding = 'latin-1')

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

### Dtypes ---> it can assign initially only with a specific data type to a column 
### ---> dtypes = {'col_1':int,'col_2':float}

In [25]:
pd.read_csv('student_depression_dataset.csv', dtype = {'Age': int, 'Work Pressure': int})

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33,Visakhapatnam,Student,5.0,0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24,Bangalore,Student,2.0,0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31,Srinagar,Student,3.0,0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28,Varanasi,Student,3.0,0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25,Jaipur,Student,4.0,0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27,Surat,Student,5.0,0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27,Ludhiana,Student,2.0,0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31,Faridabad,Student,3.0,0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18,Ludhiana,Student,5.0,0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27,Patna,Student,4.0,0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

## parse_date --> Convert the date into appropriate readale format

### CONVERTERS ---> 
#### BRING THE TRANSFORMATION ON A CONVERTER (SPECIFIC VALUE) IN A (COLUMN) & THIS CONVERTER IS A FUNCTION

In [26]:
def station(value):
    if value == 'Q':
        return 'Queenstown'
    else:
        return value

pd.read_csv('Titanic.csv', converters = {'Embarked': station})

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Queenstown
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Queenstown
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

### na_values ---> helps with mentioning what values to be considered as missing values
### na_values = [ '/' , ':' , 'NO' ]

In [29]:
pd.read_csv('Titanic.csv', na_values = ['NO', 'NaN' ])

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

## LOADING HUDE DATA
### LOAD DATA IN CHUNKS
### ---> CHUNKSIZE = NUM_VALUE ----> 5000 IN EVERY DATAFRAME 
### CHUNKSIZE IS 5000

In [31]:
dfs = pd.read_csv('student_depression_dataset.csv', chunksize = 5000)

In [32]:
for chunks in dfs:
    print(chunks.shape)

(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(2901, 18)