# AUTOMATED DATA CLEANING

## Types of missing data :-
### 
### 1. Missing Completely At Random (MCAR)
### 2. Missing At Random (MAR)
### 3. Missing Not At Random (MNAR)

In [195]:
import pandas as pd

In [196]:
df = pd.read_csv('unclean_smartwatch_health_data.csv')

In [197]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [198]:
df[df['Heart Rate (BPM)'].isnull() == True]

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,3919.0,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,3945.0,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,2981.0,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,4099.0,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...,...
9875,NaN,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,1476.0,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,1434.0,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,4907.0,NaN,98.401058,3364.788855,5.691233932149209,Active,8

### There's No Pattern between the columns that signifies the Missing Values in 'Heart Rate (BPM). This Means that It is an example of Missing Completely At Random (MCAR)

In [199]:
df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median(), inplace = True)

C:\Users\geeta\AppData\Local\Temp\ipykernel_8636\1990246577.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median(), inplace = True)

In [200]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [201]:
df[df['Blood Oxygen Level (%)'].isnull() == True]

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,1466.0,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,4380.0,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,3062.0,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,4884.0,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,1870.0,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...,...
9834,4840.0,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,3942.0,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,4028.0,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,3603.0,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,3631.0,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [202]:
df = df.drop(columns = ['User ID'])

In [203]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,75.220601,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [204]:
df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean(),inplace = True)

C:\Users\geeta\AppData\Local\Temp\ipykernel_8636\4091543091.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean(),inplace = True)

In [205]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB

In [206]:
df[df['Step Count'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
136,70.593014,97.473981,NaN,3.439287691081752,Highly_Active,6
204,75.220601,98.710637,NaN,5.756958709255954,Highly_Active,8
603,69.084103,99.627473,NaN,6.358184719715759,Highly_Active,7
716,83.258294,98.704757,NaN,5.486240700986009,Seddentary,3
739,97.506420,97.651407,NaN,7.465981460156365,Active,6
...,...,...,...,...,...,...
9097,62.072133,96.810967,NaN,5.828570383973958,Seddentary,6
9121,54.793814,99.670176,NaN,6.686430627866978,Seddentary,2
9191,101.777396,100.000000,NaN,8.07989468005159,Active,10
9527,75.220601,94.694312,NaN,4.186856483292383,Seddentary,4
9565,90.411615,95.009355,NaN,8.582820460042822,Sedentary,4

### Forward Filling --- Backward Filling Strategy
#### --> Filling the missing value from previous value is forward filling
#### --> Filling the missing value from upcoming value is backward filling

In [207]:
df['Step Count']=df['Step Count'].fillna(method = 'ffill',)

C:\Users\geeta\AppData\Local\Temp\ipykernel_8636\3169840272.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Step Count']=df['Step Count'].fillna(method = 'ffill',)

In [208]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB

### Object ---> Numeric Data ----> pandas ---> to_numeric()

In [209]:
df['Sleep Duration (hours)'] = pd.to_numeric(df['Sleep Duration (hours)'], errors = 'coerce')

In [210]:
df['Sleep Duration (hours)'].dtype

dtype('float64')

In [211]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(397)

In [212]:
df['Sleep Duration (hours)'] = df['Sleep Duration (hours)'].fillna(df['Sleep Duration (hours)'].mean())

In [213]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(0)

### For Categorical Columns ---> We can use MODE function

In [214]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(4), object(2)
memory usage: 468.9+ KB

In [215]:
df['Activity Level'].mode()

0    Seddentary
Name: Activity Level, dtype: object

In [216]:
df['Activity Level'] = df['Activity Level'].fillna('Seddentary')

In [217]:
df['Activity Level'].isnull().sum()

np.int64(0)

### constant imputation ---> when you want to film missing values with constant values like 'unknown', '-999','0'.

In [218]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  object
 5   Stress Level            9800 non-null   object
dtypes: float64(4), object(2)
memory usage: 468.9+ KB

In [219]:
df['Stress Level'] = df['Stress Level'].replace('Very High', 8)

In [220]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  object
 5   Stress Level            9800 non-null   object
dtypes: float64(4), object(2)
memory usage: 468.9+ KB

In [221]:
df['Stress Level'].value_counts()

Stress Level
2     1007
7     1006
6     1001
3      995
1      984
9      976
4      966
10     954
5      945
8      917
8       49
Name: count, dtype: int64

In [222]:
df['Stress Level'] = pd.to_numeric(df['Stress Level'], errors = 'coerce')

In [223]:
df['Stress Level'].mode()

0    2.0
Name: Stress Level, dtype: float64

In [224]:
df['Stress Level'] = df['Stress Level'].fillna(5)

In [225]:
df['Stress Level'].value_counts()

Stress Level
5.0     1145
2.0     1007
7.0     1006
6.0     1001
3.0      995
1.0      984
9.0      976
8.0      966
4.0      966
10.0     954
Name: count, dtype: int64

In [226]:
df['Stress Level'].isnull().sum()

np.int64(0)

In [227]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  object
 5   Stress Level            10000 non-null  float64
dtypes: float64(5), object(1)
memory usage: 468.9+ KB

In [228]:
df['Heart Rate (BPM)'] = df['Heart Rate (BPM)'].astype('float32')
df['Blood Oxygen Level (%)'] = df['Blood Oxygen Level (%)'].astype('float32')
df['Step Count'] = df['Step Count'].astype('float32')
df['Sleep Duration (hours)'] = df['Sleep Duration (hours)'].astype('float32')
df['Stress Level'] = df['Stress Level'].astype('float32')

In [229]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float32
 1   Blood Oxygen Level (%)  10000 non-null  float32
 2   Step Count              10000 non-null  float32
 3   Sleep Duration (hours)  10000 non-null  float32
 4   Activity Level          10000 non-null  object
 5   Stress Level            10000 non-null  float32
dtypes: float32(5), object(1)
memory usage: 273.6+ KB

In [231]:
df.to_csv('clean_smartwatch_health_data.csv', index = False)